name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Add an issue reference
        uses: kentaro-m/add-an-issue-reference-action@v1.0.0
        
